# Generated by Django 4.2.1 on 2023-06-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalCursos',
            fields=[
                ('id_Modal', models.AutoField(db_column='idModal', primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
